name: Generate HTML using Liquid and Python

on:
  on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run:  |
        python -m pip install --upgrade pip
        python -m pip install liquidpy

    - name: Generate HTML
      run: |
        python3 - << EOF
        import json
        import os
        from liquid import Liquid

        # Check if the JSON data file exists
        if not os.path.isfile('data.json'):
            print('Error: data file not found')
            exit()

        # Check if the Liquid template file exists
        if not os.path.isfile('template.html'):
            print('Error: template file not found')
            exit()

        # Load the JSON data from a file
        with open('data.json') as f:
            data = json.load(f)

        # Load the Liquid template from a file
        template = Liquid('template.html')

        # Render the template with the JSON data
        new_site = template.render(data)

        # Write the rendered output to an HTML file
        with open('index.html', 'w') as f:
            f.write(new_site)

        EOF
